export const mockDataForPlayer = {
  totalResults: -1,
  page: 1,
  limit: 30,
  data: [
    {
      id: "e35ccb65f480f15ff1f2e6ad0694612d",
      startTime: "2024-02-13T12:13:23.000Z",
      durationMs: 2582500,
      Map: { fileName: "all_that_glitters_v2.1", scriptName: "All That Glitters v2.1" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [
            { name: "Jackzo" },
            { name: "Erlias" },
            { name: "CheshireRrr" },
            { name: "Nexode" },
            { name: "Dawn005" },
            { name: "Taras0791" },
            { name: "[knb]monkerl" },
            { name: "BigTastyKevin" },
          ],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [
            { name: "General_Augustus" },
            { name: "daPMK" },
            { name: "Zaidchamp" },
            { name: "Tesh" },
            { name: "pl005" },
            { name: "worstorphan" },
            { name: "__Bear__" },
            { name: "Kaioshin" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "6fe2ca65105865db48a6a8ba64f9d60f",
      startTime: "2024-02-13T03:30:55.000Z",
      durationMs: 1297300,
      Map: { fileName: "altored_divide_bar_remake_1.6.2", scriptName: "Altored Divide Bar Remake 1.6.2" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [{ name: "Traffic" }, { name: "Xandarius" }, { name: "Irishstud14" }, { name: "Valkyrie" }],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [{ name: "urbanninja000" }, { name: "PoisonedMango" }, { name: "Narwhal" }, { name: "__Bear__" }],
          AIs: [],
        },
      ],
    },
    {
      id: "39deca65d301b8797fd50c7d42eb81c5",
      startTime: "2024-02-13T03:12:57.000Z",
      durationMs: 862700,
      Map: { fileName: "charlie_in_the_hills_remake_v1.1", scriptName: "Charlie In The Hills Remake v1.1" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [{ name: "Traffic" }, { name: "Xandarius" }, { name: "Irishstud14" }, { name: "Valkyrie" }],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [{ name: "urbanninja000" }, { name: "PoisonedMango" }, { name: "Narwhal" }, { name: "__Bear__" }],
          AIs: [],
        },
      ],
    },
    {
      id: "6517ca65fc6bbdb074c37c7cda07e6de",
      startTime: "2024-02-12T13:04:37.000Z",
      durationMs: 1660733,
      Map: { fileName: "supreme_isthmus_v1.6.3", scriptName: "Supreme Isthmus v1.6.3" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [
            { name: "chossuh" },
            { name: "Yenvon" },
            { name: "Koagant" },
            { name: "X1x2" },
            { name: "ISI_GamerZ" },
            { name: "Turel" },
            { name: "Bonte" },
            { name: "Townhall" },
          ],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [
            { name: "OceanSong" },
            { name: "TEAAAAA" },
            { name: "saturn23" },
            { name: "isbedabrick" },
            { name: "BiteMyAssets" },
            { name: "Andavarus" },
            { name: "__Bear__" },
            { name: "[CTMS]Slashomega" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "7311ca65663b08f30796988759bfb104",
      startTime: "2024-02-12T12:39:15.000Z",
      durationMs: 1210500,
      Map: { fileName: "supreme_isthmus_v1.6.3", scriptName: "Supreme Isthmus v1.6.3" },
      AllyTeams: [
        {
          winningTeam: false,
          Players: [
            { name: "Andavarus" },
            { name: "isbedabrick" },
            { name: "ISI_GamerZ" },
            { name: "chossuh" },
            { name: "saturn23" },
            { name: "Omaha" },
            { name: "OceanSong" },
            { name: "Antraxis" },
          ],
          AIs: [],
        },
        {
          winningTeam: true,
          Players: [
            { name: "MakPerdak" },
            { name: "EarthWalker" },
            { name: "Zacharias" },
            { name: "deckcommander" },
            { name: "Anoromi" },
            { name: "Smy" },
            { name: "__Bear__" },
            { name: "[CTMS]Slashomega" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "de09ca65455bc1bd0eb7c4043ec6bb51",
      startTime: "2024-02-12T12:06:54.000Z",
      durationMs: 1720867,
      Map: { fileName: "supreme_isthmus_v1.6.3", scriptName: "Supreme Isthmus v1.6.3" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [
            { name: "EldradhAFUS" },
            { name: "isbedabrick" },
            { name: "OceanSong" },
            { name: "deckcommander" },
            { name: "agoie" },
            { name: "EarthWalker" },
            { name: "ISI_GamerZ" },
            { name: "Antraxis" },
          ],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [
            { name: "saturn23" },
            { name: "[CTMS]Slashomega" },
            { name: "Zacharias" },
            { name: "Harmfulbrown25" },
            { name: "Cropz" },
            { name: "Omaha" },
            { name: "__Bear__" },
            { name: "zealo" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "b197c9654a5905d17cc14c8e31ace06a",
      startTime: "2024-02-12T03:59:45.000Z",
      durationMs: 2938367,
      Map: { fileName: "forge_v2.3", scriptName: "Forge v2.3" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [
            { name: "khakis" },
            { name: "Rimmer" },
            { name: "LadyBird" },
            { name: "AkiraSorara" },
            { name: "Goku_Uchiha_SS3" },
            { name: "ILikeAsians" },
            { name: "mcscrag" },
            { name: "Jinx128" },
          ],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [
            { name: "GMALLOY33" },
            { name: "Lancks" },
            { name: "PoisonedMango" },
            { name: "OnlyTicks" },
            { name: "Jamphone" },
            { name: "__Bear__" },
            { name: "Destro" },
            { name: "Dancingdingleberry" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "af8bc96549079f1838e46b6fbb11ca07",
      startTime: "2024-02-12T03:08:31.000Z",
      durationMs: 1920400,
      Map: { fileName: "rosetta_1.42", scriptName: "Rosetta 1.42" },
      AllyTeams: [
        {
          winningTeam: false,
          Players: [
            { name: "UncleBadTouch" },
            { name: "__Bear__" },
            { name: "Kromok" },
            { name: "Choupe" },
            { name: "urbanninja000" },
            { name: "[MASK]Soli" },
            { name: "ToninsTon" },
            { name: "PoisonedMango" },
          ],
          AIs: [],
        },
        {
          winningTeam: true,
          Players: [
            { name: "ElenaNito" },
            { name: "slim[]daddy" },
            { name: "SLOPPYGAGGER" },
            { name: "huser" },
            { name: "]OS_1_CLAN[ado" },
            { name: "Wiira" },
            { name: "kennyei" },
            { name: "Vrekrer" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "7681c9658cd7ecd6037857c0b76f6699",
      startTime: "2024-02-12T02:24:54.000Z",
      durationMs: 2086633,
      Map: { fileName: "supreme_isthmus_v1.6.3", scriptName: "Supreme Isthmus v1.6.3" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [
            { name: "Kcorp" },
            { name: "Vziuh" },
            { name: "LostHope" },
            { name: "TaxationIsTheft" },
            { name: "EthanTheEpic" },
            { name: "GreekoBratko" },
            { name: "Xordan" },
            { name: "Vilageidot" },
          ],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [
            { name: "Viable" },
            { name: "Frozt" },
            { name: "keedo" },
            { name: "bladerunner" },
            { name: "Arrun247" },
            { name: "__Bear__" },
            { name: "XTA_ApeX" },
            { name: "PoisonedMango" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "16b9c86593ed19b0c61b495b26e48e89",
      startTime: "2024-02-11T12:09:58.000Z",
      durationMs: 2704933,
      Map: { fileName: "supreme_isthmus_v1.6.3", scriptName: "Supreme Isthmus v1.6.3" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [
            { name: "KaiserGlass" },
            { name: "Leo88" },
            { name: "jMiguel" },
            { name: "Nazarid" },
            { name: "WhiteSeraph" },
            { name: "Xordan" },
            { name: "Karolson" },
            { name: "badbot" },
          ],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [
            { name: "deckcommander" },
            { name: "__Bear__" },
            { name: "400KgBut52OS" },
            { name: "LastShadow23" },
            { name: "BakeMedo" },
            { name: "Chronopolize" },
            { name: "Justa5" },
            { name: "marty_bird" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "63b1c865f89df66ae7a268259dbacf1c",
      startTime: "2024-02-11T11:37:07.000Z",
      durationMs: 1202267,
      Map: { fileName: "supreme_isthmus_v1.6.3", scriptName: "Supreme Isthmus v1.6.3" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [
            { name: "Justa5" },
            { name: "LastShadow23" },
            { name: "CavinTech" },
            { name: "deckcommander" },
            { name: "marty_bird" },
            { name: "__Bear__" },
            { name: "Kcorp" },
            { name: "400KgBut52OS" },
          ],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [
            { name: "Punjiba" },
            { name: "badbot" },
            { name: "Wind" },
            { name: "matowuut" },
            { name: "BakeMedo" },
            { name: "Karolson" },
            { name: "Chronopolize" },
            { name: "Serotos" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "1aacc86529e8662bef9b6affcb4099e1",
      startTime: "2024-02-11T11:14:34.000Z",
      durationMs: 1004633,
      Map: { fileName: "supreme_isthmus_v1.6.3", scriptName: "Supreme Isthmus v1.6.3" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [
            { name: "fiddler112" },
            { name: "LastShadow23" },
            { name: "CavinTech" },
            { name: "HatENooB" },
            { name: "deckcommander" },
            { name: "__Bear__" },
            { name: "Chronopolize" },
            { name: "badbot" },
          ],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [
            { name: "Punjiba" },
            { name: "Kcorp" },
            { name: "400KgBut52OS" },
            { name: "marty_bird" },
            { name: "BakeMedo" },
            { name: "Karolson" },
            { name: "Justa5" },
            { name: "BlandUnicorn" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "8f33c8654f2e2001f98a17c77b24a6d8",
      startTime: "2024-02-11T02:40:15.000Z",
      durationMs: 775267,
      Map: { fileName: "the_cold_place_BAR_v1.1", scriptName: "The Cold Place BAR v1.1" },
      AllyTeams: [
        {
          winningTeam: false,
          Players: [{ name: "Pyrosaurus_Rex" }, { name: "plutonic" }, { name: "tidy_yak" }],
          AIs: [],
        },
        {
          winningTeam: true,
          Players: [{ name: "PoisonedMango" }, { name: "Sargentkickass" }, { name: "__Bear__" }],
          AIs: [],
        },
      ],
    },
    {
      id: "122ec8650f05c7c53fb24e1f83ec6c30",
      startTime: "2024-02-11T02:16:50.000Z",
      durationMs: 1122667,
      Map: { fileName: "the_cold_place_BAR_v1.1", scriptName: "The Cold Place BAR v1.1" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [{ name: "Pyrosaurus_Rex" }, { name: "plutonic" }, { name: "tidy_yak" }],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [{ name: "PoisonedMango" }, { name: "Premalone15" }, { name: "__Bear__" }],
          AIs: [],
        },
      ],
    },
    {
      id: "7a7ac765f7c0f06f6310c22ed0686d89",
      startTime: "2024-02-10T13:30:34.000Z",
      durationMs: 2673800,
      Map: { fileName: "all_that_glitters_v2.1", scriptName: "All That Glitters v2.1" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [
            { name: "__Bear__" },
            { name: "Whey_eater" },
            { name: "Makemake" },
            { name: "kiansadr" },
            { name: "urbanninja000" },
            { name: "Lightwolf" },
            { name: "[ZXD]Faant" },
            { name: "Prime_Federator" },
          ],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [
            { name: "Arhimodon" },
            { name: "[ZXD]ToddAndChips" },
            { name: "DooDooLicker6" },
            { name: "malpertuis" },
            { name: "Toukitsu" },
            { name: "Ritual" },
            { name: "FelixJarl" },
            { name: "BuddZIE317" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "1f73c7659c6145391754a43f1034e076",
      startTime: "2024-02-10T12:59:11.000Z",
      durationMs: 1439333,
      Map: { fileName: "all_that_glitters_v2.1", scriptName: "All That Glitters v2.1" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [
            { name: "Raigeki" },
            { name: "DraconicViper" },
            { name: "Makemake" },
            { name: "Arhimodon" },
            { name: "BuddZIE317" },
            { name: "[ZXD]ToddAndChips" },
            { name: "[ZXD]Faant" },
            { name: "Yamee" },
          ],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [
            { name: "reddragon2010" },
            { name: "Lightwolf" },
            { name: "DooDooLicker6" },
            { name: "urbanninja000" },
            { name: "Toukitsu" },
            { name: "Ritual" },
            { name: "__Bear__" },
            { name: "DiLLiGAF23" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "ca69c76584a0b4b16b6c27c6671e3dee",
      startTime: "2024-02-10T12:19:22.000Z",
      durationMs: 1718000,
      Map: { fileName: "supreme_isthmus_v1.6.3", scriptName: "Supreme Isthmus v1.6.3" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [
            { name: "Krarilotus" },
            { name: "fiddler112" },
            { name: "Dawn005" },
            { name: "MaxMustard" },
            { name: "BubSchnoods" },
            { name: "N0Problem" },
            { name: "herrmotz" },
            { name: "PLANIAN" },
          ],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [
            { name: "Minibee2277" },
            { name: "Leszek12191" },
            { name: "Badurack" },
            { name: "__Bear__" },
            { name: "Anoromi" },
            { name: "PancakeBatterBlaster" },
            { name: "hiladoy" },
            { name: "urbanninja000" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "8f16c765f5a273e14b23727dd698e083",
      startTime: "2024-02-10T06:24:15.000Z",
      durationMs: 1630533,
      Map: { fileName: "erebos_lakes_v1.0", scriptName: "Erebos Lakes v1.0" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [
            { name: "[peeps]JAWSMUNCH" },
            { name: "aleee" },
            { name: "ThrobbinTony" },
            { name: "Goosejuice" },
            { name: "danilocspedro" },
            { name: "Mozziea" },
            { name: "GamerGuy69" },
            { name: "WarlordChewy" },
          ],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [
            { name: "zealo" },
            { name: "feller" },
            { name: "BilboTBaggins" },
            { name: "xabre" },
            { name: "Kryptos" },
            { name: "PoisonedMango" },
            { name: "__Bear__" },
            { name: "urbanninja000" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "c310c765eb9f579f318a0763cdbed782",
      startTime: "2024-02-10T05:59:31.000Z",
      durationMs: 1193033,
      Map: { fileName: "jade_empress_1.3", scriptName: "Jade Empress 1.3" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [
            { name: "[peeps]JAWSMUNCH" },
            { name: "aleee" },
            { name: "ThrobbinTony" },
            { name: "Goosejuice" },
            { name: "danilocspedro" },
            { name: "Mozziea" },
            { name: "Void_Aurora" },
            { name: "BeastEater69" },
          ],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [
            { name: "zealo" },
            { name: "urbanninja000" },
            { name: "EvilManifested" },
            { name: "feller" },
            { name: "PoisonedMango" },
            { name: "CriscoCube" },
            { name: "__Bear__" },
            { name: "GamerGuy69" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "6b08c7658d102bf119908c25be3ab86d",
      startTime: "2024-02-10T05:23:55.000Z",
      durationMs: 1603533,
      Map: { fileName: "supreme_isthmus_v1.6.3", scriptName: "Supreme Isthmus v1.6.3" },
      AllyTeams: [
        {
          winningTeam: false,
          Players: [
            { name: "bladerunner" },
            { name: "hiladoy" },
            { name: "tkejeremy" },
            { name: "Agonist" },
            { name: "ALLPROABE" },
            { name: "GamerGuy69" },
            { name: "G0DeaterXx" },
            { name: "Mons" },
          ],
          AIs: [],
        },
        {
          winningTeam: true,
          Players: [
            { name: "Gaspard" },
            { name: "urbanninja000" },
            { name: "Koagant" },
            { name: "HatENooB" },
            { name: "Fluffyy" },
            { name: "PoisonedMango" },
            { name: "__Bear__" },
            { name: "DoseMe" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "ba30c6652d8f73aea54f0b79493423c5",
      startTime: "2024-02-09T14:03:38.000Z",
      durationMs: 1728600,
      Map: { fileName: "supreme_isthmus_v1.6.3", scriptName: "Supreme Isthmus v1.6.3" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [
            { name: "Knock_Knock" },
            { name: "__Bear__" },
            { name: "Minibee2277" },
            { name: "losscreen" },
            { name: "beastypet" },
            { name: "Godzilla[GTR_R32]" },
            { name: "Renasonz" },
            { name: "REDDDDDDDD" },
          ],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [
            { name: "[CTMS]Slashomega" },
            { name: "RoboAlphaChad" },
            { name: "synergy42" },
            { name: "Yenvon" },
            { name: "deckcommander" },
            { name: "Andavarus" },
            { name: "Pinkgeneral" },
            { name: "orzoon" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "87efc565eaeae9865d7b9424c804c698",
      startTime: "2024-02-09T09:25:27.000Z",
      durationMs: 2746400,
      Map: { fileName: "supreme_isthmus_v1.6.3", scriptName: "Supreme Isthmus v1.6.3" },
      AllyTeams: [
        {
          winningTeam: false,
          Players: [
            { name: "Fatpanda" },
            { name: "UselesS15" },
            { name: "Megax780" },
            { name: "Madsocks" },
            { name: "BARkeeper" },
            { name: "Zeeburg" },
            { name: "mfrakhman" },
            { name: "SamsoniteMines" },
          ],
          AIs: [],
        },
        {
          winningTeam: true,
          Players: [
            { name: "No_Winning" },
            { name: "Barakamont" },
            { name: "Swiftn" },
            { name: "IamDave" },
            { name: "Cryocore" },
            { name: "X1x2" },
            { name: "__Bear__" },
            { name: "Dachs" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "b9e8c56507b7c88b768ba58089515e5e",
      startTime: "2024-02-09T08:56:25.000Z",
      durationMs: 1394900,
      Map: { fileName: "supreme_isthmus_v1.6.3", scriptName: "Supreme Isthmus v1.6.3" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [
            { name: "Anoromi" },
            { name: "__Bear__" },
            { name: "IamDave" },
            { name: "X1x2" },
            { name: "Megax780" },
            { name: "Dachs" },
            { name: "TheMuffinman" },
            { name: "Smy" },
          ],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [
            { name: "Kran" },
            { name: "Tharsis" },
            { name: "jetmistro" },
            { name: "mfrakhman" },
            { name: "Barakamont" },
            { name: "No_Winning" },
            { name: "Fatpanda" },
            { name: "Argalia" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "2a9bc5651d4a8e7e4107837836a8e724",
      startTime: "2024-02-09T03:25:30.000Z",
      durationMs: 2404633,
      Map: { fileName: "jade_empress_1.3", scriptName: "Jade Empress 1.3" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [
            { name: "Dasvoid" },
            { name: "bingbingbang" },
            { name: "Milkjunky" },
            { name: "Archi" },
            { name: "Zelfrur" },
            { name: "TheBattleBandit" },
            { name: "19chiodowi" },
            { name: "zaidka" },
          ],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [
            { name: "katanova" },
            { name: "dogtime" },
            { name: "BonePadre" },
            { name: "__Bear__" },
            { name: "constructTurret_666" },
            { name: "hatow" },
            { name: "[Jammacus]NightFury" },
            { name: "PoisonedMango" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "3194c5651c8a78173825ff7cbd24c96e",
      startTime: "2024-02-09T02:55:45.000Z",
      durationMs: 1412267,
      Map: { fileName: "salt_reef_v0.9", scriptName: "Salt Reef v0.9" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [
            { name: "Dasvoid" },
            { name: "Dessfoxx" },
            { name: "BonePadre" },
            { name: "Archi" },
            { name: "Zelfrur" },
            { name: "dogtime" },
            { name: "Milkjunky" },
            { name: "zaidka" },
          ],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [
            { name: "Yanka" },
            { name: "tkejeremy" },
            { name: "nub1" },
            { name: "__Bear__" },
            { name: "TheBattleBandit" },
            { name: "PoisonedMango" },
            { name: "[Jammacus]NightFury" },
            { name: "katanova" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "66d2c465b10ef246cb546d6e671c7c68",
      startTime: "2024-02-08T13:08:54.000Z",
      durationMs: 1530700,
      Map: { fileName: "supreme_isthmus_v1.6.3", scriptName: "Supreme Isthmus v1.6.3" },
      AllyTeams: [
        {
          winningTeam: false,
          Players: [
            { name: "Kcorp" },
            { name: "Compa" },
            { name: "ocelox" },
            { name: "Deevz" },
            { name: "Buijsinator" },
            { name: "deckcommander" },
            { name: "__Bear__" },
            { name: "MrElusive" },
          ],
          AIs: [],
        },
        {
          winningTeam: true,
          Players: [
            { name: "Alexspeed" },
            { name: "RG22" },
            { name: "Unrelenting" },
            { name: "Sillywilly" },
            { name: "DARKKNIGHTXALPHA" },
            { name: "GTM" },
            { name: "klaboem" },
            { name: "Arrun247" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "1f4ac46598f34c0894ed1644e34b4761",
      startTime: "2024-02-08T03:27:27.000Z",
      durationMs: 1259533,
      Map: { fileName: "supreme_isthmus_v1.6.3", scriptName: "Supreme Isthmus v1.6.3" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [
            { name: "PoisonedMango" },
            { name: "__Bear__" },
            { name: "Twiner" },
            { name: "gamercore" },
            { name: "Nutt_" },
            { name: "Looni" },
            { name: "Panamajacks" },
            { name: "Kappricorn" },
          ],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [
            { name: "jjspeed" },
            { name: "Marcin87" },
            { name: "divix666" },
            { name: "Mardock" },
            { name: "JackieBoy" },
            { name: "gergsthegreat" },
            { name: "watchnlearn" },
            { name: "UselesS15" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "eb74c3654e41757973102f9188b2ed12",
      startTime: "2024-02-07T12:17:47.000Z",
      durationMs: 2503867,
      Map: { fileName: "supreme_isthmus_v1.6.3", scriptName: "Supreme Isthmus v1.6.3" },
      AllyTeams: [
        {
          winningTeam: false,
          Players: [
            { name: "mfrakhman" },
            { name: "Longdong" },
            { name: "kabab" },
            { name: "Skedaddle" },
            { name: "Skarjack" },
            { name: "RollingPanzers" },
            { name: "LEGIONxPHANTOM" },
            { name: "Jardead" },
          ],
          AIs: [],
        },
        {
          winningTeam: true,
          Players: [
            { name: "Thoth" },
            { name: "Dasvoid" },
            { name: "Hbullet" },
            { name: "AimTime" },
            { name: "Kirky" },
            { name: "Archi" },
            { name: "__Bear__" },
            { name: "0verP0wer" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "03fac26554a630368653c0c1e9ac03bf",
      startTime: "2024-02-07T03:33:23.000Z",
      durationMs: 1515967,
      Map: { fileName: "supreme_isthmus_v1.6.3", scriptName: "Supreme Isthmus v1.6.3" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [
            { name: "__Bear__" },
            { name: "Will11" },
            { name: "AnarchyBBK" },
            { name: "Desty" },
            { name: "Reaperc373" },
            { name: "PoisonedMango" },
            { name: "Hbullet" },
            { name: "420bongsmoker420" },
          ],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [
            { name: "Mozziea" },
            { name: "Actaea" },
            { name: "Omaha" },
            { name: "Looni" },
            { name: "numenor" },
            { name: "isbedabrick" },
            { name: "Maverick_Powers" },
            { name: "Symbiosis" },
          ],
          AIs: [],
        },
      ],
    },
    {
      id: "a3f4c2657ddac898f4f478dd8ee8b11c",
      startTime: "2024-02-07T03:10:27.000Z",
      durationMs: 1170833,
      Map: { fileName: "supreme_isthmus_v1.6.3", scriptName: "Supreme Isthmus v1.6.3" },
      AllyTeams: [
        {
          winningTeam: true,
          Players: [
            { name: "__Bear__" },
            { name: "Will11" },
            { name: "dogeboom" },
            { name: "Omaha" },
            { name: "Stoyko" },
            { name: "420bongsmoker420" },
            { name: "PoisonedMango" },
            { name: "StanleyDuck" },
          ],
          AIs: [],
        },
        {
          winningTeam: false,
          Players: [
            { name: "glizzyglobbler" },
            { name: "Actaea" },
            { name: "Mozziea" },
            { name: "Looni" },
            { name: "numenor" },
            { name: "Hbullet" },
            { name: "isbedabrick" },
            { name: "Reaperc373" },
          ],
          AIs: [],
        },
      ],
    },
  ],
};
export const mockDataForReplay = {
  id: "e35ccb65f480f15ff1f2e6ad0694612d",
  fileName: "2024-02-13_12-13-23-021_All That Glitters v2_105.1.1-2303-g5f26a29 BAR105.sdfz",
  engineVersion: "105.1.1-2303-g5f26a29 BAR105",
  gameVersion: "Beyond All Reason test-25240-3cdcf87",
  startTime: "2024-02-13T12:13:23.000Z",
  durationMs: 2582500,
  fullDurationMs: 2806000,
  hostSettings: {
    ishost: "1",
    hostip: "",
    numallyteams: "2",
    numteams: "16",
    startpostype: "2",
    gametype: "Beyond All Reason test-25240-3cdcf87",
    hosttype: "SPADS",
    mapname: "All That Glitters v2.1",
    autohostport: "53101",
    numrestrictions: "0",
    autohostname: "[teh]clusterEU3[01]",
    autohostrank: "0",
    autohostaccountid: "45660",
    numplayers: "21",
    autohostcountrycode: "US",
    hostport: "53201",
  },
  gameSettings: {
    experimentalrebalancet2energy: "0",
    transportenemy: "notcoms",
    experimentalextraunits: "0",
    maxunits: "2000",
    tweakunits3: "",
    multiplier_maxdamage: "1",
    raptor_firstwavesboost: "1",
    unit_restrictions_noair: "0",
    metalperpoint: "1",
    raptor_raptorstart: "initialbox",
    assistdronescount: "10",
    disablemapdamage: "0",
    scav_spawntimemult: "1",
    experimentalrebalancet2metalextractors: "0",
    multiplier_metalcost: "1",
    tweakunits: "",
    experimentalreversegear: "0",
    debugcommands: "",
    allowpausegameplay: "1",
    captureradius: "100",
    multiplier_energyproduction: "1",
    unit_restrictions_nonukes: "0",
    scav_spawncountmult: "1",
    decapspeed: "2",
    multiplier_builddistance: "1",
    multiplier_energycost: "1",
    tweakdefs3: "",
    assistdronesair: "1",
    limitscore: "300",
    unified_maxslope: "0",
    startenergy: "1000",
    scoremode_chess_unbalanced: "0",
    tweakdefs2: "",
    ruins_civilian_disable: "0",
    startmetal: "1000",
    teamffa_start_boxes_shuffle: "1",
    usemexconfig: "0",
    experimentalnoaircollisions: "0",
    raptor_spawncountmult: "1",
    usemapconfig: "1",
    norush: "0",
    lootboxes: "scav_only",
    ffa_wreckage: "0",
    raptor_queentimemult: "1",
    tugofwarmodifier: "4",
    multiplier_weaponrange: "1",
    capturetime: "30",
    multiplier_maxvelocity: "1",
    scav_graceperiodmult: "1",
    tweakunits9: "",
    ruins_density: "normal",
    assistdronesenabled: "disabled",
    experimentalstandardgravity: "mapgravity",
    tweakdefs7: "",
    map_waterlevel: "0",
    scav_difficulty: "normal",
    unit_restrictions_notech3: "0",
    unit_restrictions_notech2: "0",
    scoremode_chess_adduptime: "1",
    multiplier_shieldpower: "1",
    tweakdefs5: "",
    commanderbuildersenabled: "disabled",
    tweakdefs: "",
    unit_restrictions_noconverters: "0",
    emprework: "0",
    raptor_graceperiodmult: "1",
    tweakdefs9: "",
    dominationscoretime: "30",
    tweakunits4: "",
    experimentalxpgain: "1",
    experimentalmassoverride: "0",
    multiplier_buildpower: "1",
    teamcolors_icon_dev_mode: "disabled",
    scav_scavstart: "initialbox",
    assistdronesbuildpowermultiplier: "1",
    ruins: "scav_only",
    ruins_only_t1: "1",
    multiplier_buildtimecost: "1",
    capturebonus: "100",
    starttime: "0",
    multiplier_resourceincome: "1",
    scoremode_chess: "1",
    tweakdefs8: "",
    map_tidal: "unchanged",
    unit_restrictions_nolrpc: "0",
    dominationscore: "1000",
    unit_restrictions_noextractors: "0",
    multiplier_turnrate: "1",
    tweakdefs1: "",
    norushtimer: "5",
    raptor_spawntimemult: "1",
    tweakunits2: "",
    tweakunits8: "",
    lootboxes_density: "normal",
    multiplier_energyconversion: "1",
    allowuserwidgets: "1",
    shareddynamicalliancevictory: "0",
    energyperpoint: "75",
    tweakunits5: "",
    unit_restrictions_notacnukes: "0",
    experimentallegionfaction: "0",
    experimentalshields: "unchanged",
    startenergystorage: "1000",
    experimentalimprovedtransports: "0",
    scoremode: "disabled",
    experimentalrebalancewreckstandarization: "1",
    numberofcontrolpoints: "13",
    startmetalstorage: "1000",
    map_atmosphere: "1",
    lategame_rebalance: "0",
    faction_limiter: "",
    multiplier_metalextraction: "1",
    tweakunits6: "",
    multiplier_losrange: "1",
    tweakdefs4: "",
    scav_endless: "0",
    disable_fogofwar: "0",
    tweakunits1: "",
    experimentalrebalancet2labs: "0",
    ranked_game: "1",
    fixedallies: "1",
    coop: "0",
    scoremode_chess_spawnsperphase: "1",
    scav_bosstimemult: "1",
    critters: "1",
    tweakunits7: "",
    commanderbuildersrange: "1000",
    defaultdecals: "1",
    multiplier_weapondamage: "1",
    raptor_difficulty: "normal",
    multiplier_radarrange: "1",
    map_waterislava: "0",
    commanderbuildersbuildpower: "400",
    releasecandidates: "1",
    raptor_endless: "0",
    tweakdefs6: "",
    teamcolors_anonymous_mode: "disabled",
    ai_incomemultiplier: "1",
    deathmode: "com",
    air_rework: "0",
  },
  mapSettings: { dry: "0" },
  spadsSettings: {
    clanmode: "tag(5):pref(5)",
    autobalance: "advanced",
    colorsensitivity: "-1",
    nbplayerbyid: "1",
    rankmode: "account",
    minplayers: "1",
    botsrank: "3",
    extrabox: "0",
    forcestarted: "0",
    maxspecs: "",
    autostop: "gameOver",
    nospecdraw: "0",
    autoaddbotnb: "0",
    springservertype: "dedicated",
    autostart: "off",
    speedcontrol: "2",
    autofixcolors: "off",
    autospecextraplayers: "1",
    skillmode: "rank",
    minteamsize: "1",
    autoblockcolors: "0",
    teamsize: "8",
    idsharemode: "off",
    autoblockbalance: "1",
    nbteams: "2",
    spadsversion: "0.13.26",
    nospecchat: "0",
    balancemode: "clan:skill",
  },
  gameEndedNormally: true,
  hasBots: false,
  preset: "team",
  reported: false,
  awards: {
    econDestroyed: [
      { teamId: 12, value: 2748025 },
      { teamId: 10, value: 1197580 },
      { teamId: 3, value: 80870 },
    ],
    fightingUnitsDestroyed: [
      { teamId: 12, value: 18632062 },
      { teamId: 1, value: 10606210 },
      { teamId: 3, value: 9748000 },
    ],
    resourceEfficiency: [
      { teamId: 12, value: 1.52886152 },
      { teamId: 9, value: 0.36984247 },
      { teamId: 0, value: 0.27423704 },
    ],
    cow: { teamId: 12 },
    mostResourcesProduced: { teamId: 1, value: 67684736 },
    mostDamageTaken: { teamId: 1, value: 950861.875 },
    sleep: { teamId: 1, value: 1586.1333 },
  },
  createdAt: "2024-02-13T13:00:53.587Z",
  updatedAt: "2024-02-13T13:00:53.587Z",
  mapId: 337,
  Map: { id: 337, scriptName: "All That Glitters v2.1", fileName: "all_that_glitters_v2.1", width: 12, height: 20 },
  AllyTeams: [
    {
      id: 1341973,
      allyTeamId: 0,
      startBox: { bottom: 1, left: 0, top: 0.8, right: 1 },
      winningTeam: false,
      createdAt: "2024-02-13T13:00:53.605Z",
      updatedAt: "2024-02-13T13:00:53.605Z",
      demoId: "e35ccb65f480f15ff1f2e6ad0694612d",
      Players: [
        {
          id: 4501944,
          playerId: 5,
          name: "Kaioshin",
          teamId: 5,
          handicap: 0,
          faction: "Cortex",
          countryCode: "DE",
          rgbColor: { b: 47, g: 112, r: 27 },
          rank: 4,
          skillUncertainty: 2.01,
          skill: "[9.2]",
          trueSkill: null,
          startPos: { x: 5469, y: 178.50048828125, z: 9522 },
          clanId: null,
          trueSkillMuBefore: null,
          trueSkillSigmaBefore: null,
          trueSkillMuAfter: null,
          trueSkillSigmaAfter: null,
          createdAt: "2024-02-13T13:00:54.064Z",
          updatedAt: "2024-02-13T13:00:54.068Z",
          allyTeamId: 1341973,
          userId: 48587,
        },
        {
          id: 4501931,
          playerId: 4,
          name: "General_Augustus",
          teamId: 4,
          handicap: 0,
          faction: "Cortex",
          countryCode: "FR",
          rgbColor: { b: 148, g: 255, r: 143 },
          rank: 4,
          skillUncertainty: 2.04,
          skill: "[12.51]",
          trueSkill: null,
          startPos: { x: 5160, y: 178.494140625, z: 8200 },
          clanId: null,
          trueSkillMuBefore: null,
          trueSkillSigmaBefore: null,
          trueSkillMuAfter: null,
          trueSkillSigmaAfter: null,
          createdAt: "2024-02-13T13:00:53.710Z",
          updatedAt: "2024-02-13T13:00:53.715Z",
          allyTeamId: 1341973,
          userId: 169469,
        },
        {
          id: 4501932,
          playerId: 2,
          name: "daPMK",
          teamId: 2,
          handicap: 0,
          faction: "Armada",
          countryCode: "NO",
          rgbColor: { b: 229, g: 245, r: 0 },
          rank: 4,
          skillUncertainty: 2.37,
          skill: "[18.27]",
          trueSkill: null,
          startPos: { x: 655, y: 171.3951416015625, z: 8197 },
          clanId: null,
          trueSkillMuBefore: null,
          trueSkillSigmaBefore: null,
          trueSkillMuAfter: null,
          trueSkillSigmaAfter: null,
          createdAt: "2024-02-13T13:00:53.744Z",
          updatedAt: "2024-02-13T13:00:53.754Z",
          allyTeamId: 1341973,
          userId: 56774,
        },
        {
          id: 4501936,
          playerId: 3,
          name: "Zaidchamp",
          teamId: 3,
          handicap: 0,
          faction: "Armada",
          countryCode: "US",
          rgbColor: { b: 242, g: 65, r: 105 },
          rank: 4,
          skillUncertainty: 2.8,
          skill: "[16.07]",
          trueSkill: null,
          startPos: { x: 1955, y: 169.002197265625, z: 9634 },
          clanId: null,
          trueSkillMuBefore: null,
          trueSkillSigmaBefore: null,
          trueSkillMuAfter: null,
          trueSkillSigmaAfter: null,
          createdAt: "2024-02-13T13:00:53.863Z",
          updatedAt: "2024-02-13T13:00:53.867Z",
          allyTeamId: 1341973,
          userId: 51944,
        },
        {
          id: 4501938,
          playerId: 6,
          name: "Tesh",
          teamId: 6,
          handicap: 0,
          faction: "Armada",
          countryCode: "AU",
          rgbColor: { b: 255, g: 194, r: 124 },
          rank: 1,
          skillUncertainty: 6.78,
          skill: "[7.2]",
          trueSkill: null,
          startPos: { x: 3195, y: 178.2353515625, z: 8267 },
          clanId: null,
          trueSkillMuBefore: null,
          trueSkillSigmaBefore: null,
          trueSkillMuAfter: null,
          trueSkillSigmaAfter: null,
          createdAt: "2024-02-13T13:00:53.914Z",
          updatedAt: "2024-02-13T13:00:53.917Z",
          allyTeamId: 1341973,
          userId: 203908,
        },
        {
          id: 4501939,
          playerId: 7,
          name: "pl005",
          teamId: 7,
          handicap: 0,
          faction: "Cortex",
          countryCode: "RU",
          rgbColor: { b: 255, g: 148, r: 162 },
          rank: 3,
          skillUncertainty: 5.21,
          skill: "[6.71]",
          trueSkill: null,
          startPos: { x: 3480, y: 176.111328125, z: 9680 },
          clanId: null,
          trueSkillMuBefore: null,
          trueSkillSigmaBefore: null,
          trueSkillMuAfter: null,
          trueSkillSigmaAfter: null,
          createdAt: "2024-02-13T13:00:53.937Z",
          updatedAt: "2024-02-13T13:00:53.941Z",
          allyTeamId: 1341973,
          userId: 186861,
        },
        {
          id: 4501940,
          playerId: 1,
          name: "worstorphan",
          teamId: 1,
          handicap: 0,
          faction: "Cortex",
          countryCode: "US",
          rgbColor: { b: 8, g: 233, r: 12 },
          rank: 3,
          skillUncertainty: 3.13,
          skill: "[19.91]",
          trueSkill: null,
          startPos: { x: 317, y: 168.3702392578125, z: 9649 },
          clanId: null,
          trueSkillMuBefore: null,
          trueSkillSigmaBefore: null,
          trueSkillMuAfter: null,
          trueSkillSigmaAfter: null,
          createdAt: "2024-02-13T13:00:53.957Z",
          updatedAt: "2024-02-13T13:00:53.961Z",
          allyTeamId: 1341973,
          userId: 5725,
        },
        {
          id: 4501943,
          playerId: 0,
          name: "__Bear__",
          teamId: 0,
          handicap: 0,
          faction: "Cortex",
          countryCode: "JP",
          rgbColor: { b: 243, g: 62, r: 11 },
          rank: 4,
          skillUncertainty: 1.64,
          skill: "[33.51]",
          trueSkill: null,
          startPos: { x: 1830, y: 176.3203125, z: 8229 },
          clanId: null,
          trueSkillMuBefore: null,
          trueSkillSigmaBefore: null,
          trueSkillMuAfter: null,
          trueSkillSigmaAfter: null,
          createdAt: "2024-02-13T13:00:54.033Z",
          updatedAt: "2024-02-13T13:00:54.038Z",
          allyTeamId: 1341973,
          userId: 108724,
        },
      ],
      AIs: [],
    },
    {
      id: 1341972,
      allyTeamId: 1,
      startBox: { bottom: 0.2, left: 0, top: 0, right: 1 },
      winningTeam: true,
      createdAt: "2024-02-13T13:00:53.600Z",
      updatedAt: "2024-02-13T13:00:53.600Z",
      demoId: "e35ccb65f480f15ff1f2e6ad0694612d",
      Players: [
        {
          id: 4501929,
          playerId: 8,
          name: "Jackzo",
          teamId: 8,
          handicap: 0,
          faction: "Armada",
          countryCode: "GB",
          rgbColor: { b: 5, g: 16, r: 255 },
          rank: 4,
          skillUncertainty: 2.7,
          skill: "[27.26]",
          trueSkill: null,
          startPos: { x: 3048, y: 177.97933959960938, z: 1984 },
          clanId: null,
          trueSkillMuBefore: null,
          trueSkillSigmaBefore: null,
          trueSkillMuAfter: null,
          trueSkillSigmaAfter: null,
          createdAt: "2024-02-13T13:00:53.634Z",
          updatedAt: "2024-02-13T13:00:53.642Z",
          allyTeamId: 1341972,
          userId: 56540,
        },
        {
          id: 4501930,
          playerId: 14,
          name: "Erlias",
          teamId: 14,
          handicap: 0,
          faction: "Armada",
          countryCode: "DE",
          rgbColor: { b: 179, g: 144, r: 241 },
          rank: 2,
          skillUncertainty: 5.14,
          skill: "[6.66]",
          trueSkill: null,
          startPos: { x: 773, y: 178.4901123046875, z: 846 },
          clanId: null,
          trueSkillMuBefore: null,
          trueSkillSigmaBefore: null,
          trueSkillMuAfter: null,
          trueSkillSigmaAfter: null,
          createdAt: "2024-02-13T13:00:53.676Z",
          updatedAt: "2024-02-13T13:00:53.686Z",
          allyTeamId: 1341972,
          userId: 157806,
        },
        {
          id: 4501933,
          playerId: 15,
          name: "CheshireRrr",
          teamId: 15,
          handicap: 0,
          faction: "Armada",
          countryCode: "RU",
          rgbColor: { b: 47, g: 139, r: 200 },
          rank: 2,
          skillUncertainty: 5.91,
          skill: "[3]",
          trueSkill: null,
          startPos: { x: 4299, y: 177.95849609375, z: 1982 },
          clanId: null,
          trueSkillMuBefore: null,
          trueSkillSigmaBefore: null,
          trueSkillMuAfter: null,
          trueSkillSigmaAfter: null,
          createdAt: "2024-02-13T13:00:53.779Z",
          updatedAt: "2024-02-13T13:00:53.782Z",
          allyTeamId: 1341972,
          userId: 87260,
        },
        {
          id: 4501934,
          playerId: 12,
          name: "Nexode",
          teamId: 12,
          handicap: 0,
          faction: "Cortex",
          countryCode: "BE",
          rgbColor: { b: 164, g: 238, r: 252 },
          rank: 3,
          skillUncertainty: 2.74,
          skill: "[14.71]",
          trueSkill: null,
          startPos: { x: 2814, y: 177.85205078125, z: 750 },
          clanId: null,
          trueSkillMuBefore: null,
          trueSkillSigmaBefore: null,
          trueSkillMuAfter: null,
          trueSkillSigmaAfter: null,
          createdAt: "2024-02-13T13:00:53.809Z",
          updatedAt: "2024-02-13T13:00:53.813Z",
          allyTeamId: 1341972,
          userId: 120230,
        },
        {
          id: 4501935,
          playerId: 13,
          name: "Dawn005",
          teamId: 13,
          handicap: 0,
          faction: "Cortex",
          countryCode: "AU",
          rgbColor: { b: 40, g: 40, r: 138 },
          rank: 3,
          skillUncertainty: 2.6,
          skill: "[8.68]",
          trueSkill: null,
          startPos: { x: 1131, y: 178.4793701171875, z: 1955 },
          clanId: null,
          trueSkillMuBefore: null,
          trueSkillSigmaBefore: null,
          trueSkillMuAfter: null,
          trueSkillSigmaAfter: null,
          createdAt: "2024-02-13T13:00:53.834Z",
          updatedAt: "2024-02-13T13:00:53.838Z",
          allyTeamId: 1341972,
          userId: 90793,
        },
        {
          id: 4501937,
          playerId: 10,
          name: "Taras0791",
          teamId: 10,
          handicap: 0,
          faction: "Cortex",
          countryCode: "UA",
          rgbColor: { b: 7, g: 97, r: 255 },
          rank: 3,
          skillUncertainty: 2.46,
          skill: "[19.51]",
          trueSkill: null,
          startPos: { x: 4199, y: 169.4033203125, z: 616 },
          clanId: null,
          trueSkillMuBefore: null,
          trueSkillSigmaBefore: null,
          trueSkillMuAfter: null,
          trueSkillSigmaAfter: null,
          createdAt: "2024-02-13T13:00:53.890Z",
          updatedAt: "2024-02-13T13:00:53.893Z",
          allyTeamId: 1341972,
          userId: 167545,
        },
        {
          id: 4501941,
          playerId: 9,
          name: "[knb]monkerl",
          teamId: 9,
          handicap: 0,
          faction: "Cortex",
          countryCode: "DE",
          rgbColor: { b: 0, g: 210, r: 255 },
          rank: 3,
          skillUncertainty: 4.3,
          skill: "[22.16]",
          trueSkill: null,
          startPos: { x: 5780, y: 174.80078125, z: 634 },
          clanId: null,
          trueSkillMuBefore: null,
          trueSkillSigmaBefore: null,
          trueSkillMuAfter: null,
          trueSkillSigmaAfter: null,
          createdAt: "2024-02-13T13:00:53.985Z",
          updatedAt: "2024-02-13T13:00:53.989Z",
          allyTeamId: 1341972,
          userId: 161136,
        },
        {
          id: 4501942,
          playerId: 11,
          name: "BigTastyKevin",
          teamId: 11,
          handicap: 0,
          faction: "Armada",
          countryCode: "DE",
          rgbColor: { b: 137, g: 8, r: 248 },
          rank: 2,
          skillUncertainty: 7.89,
          skill: "[18.02]",
          trueSkill: null,
          startPos: { x: 5451, y: 172.873046875, z: 2016 },
          clanId: null,
          trueSkillMuBefore: null,
          trueSkillSigmaBefore: null,
          trueSkillMuAfter: null,
          trueSkillSigmaAfter: null,
          createdAt: "2024-02-13T13:00:54.006Z",
          updatedAt: "2024-02-13T13:00:54.009Z",
          allyTeamId: 1341972,
          userId: 199350,
        },
      ],
      AIs: [],
    },
  ],
  Spectators: [
    {
      id: 1162596,
      playerId: 16,
      name: "adswrx",
      countryCode: "AU",
      rank: 3,
      skillUncertainty: 2.18,
      skill: "[21.59]",
      createdAt: "2024-02-13T13:00:54.095Z",
      updatedAt: "2024-02-13T13:00:54.101Z",
      demoId: "e35ccb65f480f15ff1f2e6ad0694612d",
      userId: 181922,
    },
    {
      id: 1162597,
      playerId: 18,
      name: "DrCox",
      countryCode: "RU",
      rank: 3,
      skillUncertainty: 6.17,
      skill: "[12.97]",
      createdAt: "2024-02-13T13:00:54.120Z",
      updatedAt: "2024-02-13T13:00:54.124Z",
      demoId: "e35ccb65f480f15ff1f2e6ad0694612d",
      userId: 69882,
    },
    {
      id: 1162598,
      playerId: 19,
      name: "CalmishPhill",
      countryCode: "US",
      rank: 2,
      skillUncertainty: 6.19,
      skill: "[11.54]",
      createdAt: "2024-02-13T13:00:54.148Z",
      updatedAt: "2024-02-13T13:00:54.152Z",
      demoId: "e35ccb65f480f15ff1f2e6ad0694612d",
      userId: 200298,
    },
    {
      id: 1162599,
      playerId: 20,
      name: "KruZar",
      countryCode: "??",
      rank: 3,
      skillUncertainty: 3.49,
      skill: "[3.41]",
      createdAt: "2024-02-13T13:00:54.182Z",
      updatedAt: "2024-02-13T13:00:54.186Z",
      demoId: "e35ccb65f480f15ff1f2e6ad0694612d",
      userId: 190969,
    },
    {
      id: 1162600,
      playerId: 17,
      name: "iHATEkpop",
      countryCode: "??",
      rank: 2,
      skillUncertainty: 8.33,
      skill: "[16.67]",
      createdAt: "2024-02-13T13:00:54.204Z",
      updatedAt: "2024-02-13T13:00:54.207Z",
      demoId: "e35ccb65f480f15ff1f2e6ad0694612d",
      userId: 195782,
    },
  ],
};
